import { Tajawal } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/home/Navbar";
import SearchBarHome from "@/components/home/SearchBarHome";

const tajawal = Tajawal({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "700", "800", "900"]
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  icons: {
    type: 'image/svg',
    icon: '/logo.svg',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={tajawal.className}>
        {children}
        <Toaster />
      </body>

    </html>
  );
}
